language: php

php:
  - 5.5
  - 5.6
  - 7.0

install:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

before_script:
  - php -S 127.0.0.1:8000 src/routes.php -t public &
  - sleep 3

script: php vendor/bin/phpunit
